fix

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -24,7 +24,7 @@ jobs:
       - name: Check if package version has been updated
         id: check-version
         run: |
-          git fetch origin develop --verbose
+          git fetch origin develop --verbose || echo "Fetch failed with exit code $?"
           VERSION_CHANGED=$(git diff --name-only origin/develop..HEAD | grep 'package.json')
           if [ "$VERSION_CHANGED" != "" ]; then
             echo "::set-output name=version_updated::true"
